### ISSUE TITLE
What does "WL" mean in remoteWL

### ISSUE THREAD

**Issue by yaeljiao** [bethrobson/Head-First-Design-Patterns#17]
I found that two packages named "remote" and "remoteWL" in command pattern. What does "WL" means here ?

**Comment by bethrobson** [comment]
"With Lambda" - where I use lambda expressions to represent the commands. If you look in the version of the book I updated in 2014 you'll see how you can replace some classes with lambda expressions (eliminating some classes and making the code smaller).

**Comment by yaeljiao** [comment]
Thanks your response! I think it's time for me to learn lambda expressions :smiley:
