### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MAPeacock86** [bethrobson/Head-First-Design-Patterns#22]
Is there an open source license for this code? I'm in the process of working through the book and I'm writing the examples in C# and would like to post a public repository, but don't know what attribution would be needed or if that would fall under acceptable use.

**Comment by bethrobson** [comment]
We don't officially have a license on it, but if you could think of it like CC with attribution that would be great. Please refer to the book and the original code in your attribution. Thank you!

**Comment by MAPeacock86** [comment]
Thanks! I planned to do just that.

**Comment by allentiak** [comment]
Why don't you just put it under Apache 2 and ask (but not require) for proper attribution? AFAIK, CC-Attribution is not aimed at software...

**Comment by allentiak** [comment]
https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software
