### ISSUE TITLE
Question of ArrayList type in Iterator Pattern

### ISSUE THREAD

**Issue by wuyh115** [bethrobson/Head-First-Design-Patterns#3]
package headfirst.designpatterns.iterator.transition;
import java.util.*;
public class Waitress {
	ArrayList\<MenuItem\> menus;

The code in page 360 defined the ArrayList as type Menu. However, in git repo, the type is MenuItem.
As I understand, the type should be Menu. Could you please help confirm whether I am correct?

Thank you for your help in advance.

**Comment by bethrobson** [comment]
Hi,
You are right! I've fixed the code in the /transition package and also added some code for testing purposes.

Thank you!

Elisabeth
